FROM ghcr.io/faytranevozter/php:8.3-cli

# Install build dependencies for PECL extensions
RUN apk add --no-cache --virtual .build-deps \
        autoconf \
        g++ \
        make \
        openssl-dev \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb \
    && apk del .build-deps
